### ISSUE TITLE
bug: regression on nuxt@3.13.2 breaking the module

### ISSUE THREAD

**Issue by CodeXiD** [Gugustinette/nuxt-maplibre#2]
Hi I would like to use this package, I installed it

`npx nuxi@latest module add nuxt-maplibre`

After that I set `ssr: false` and wrapped the map in `<ClientOnly>` but unfortunately I get the following error

`Uncaught SyntaxError: The requested module '/_nuxt/node_modules/@indoorequal/vue-maplibre-gl/dist/vue-maplibre-gl.umd.js?v=3efd9a54' does not provide an export named 'MglNavigationControl' (at app.vue:1:148)`

Dependencies:
`
"nuxt": "^3.13.0",
"nuxt-maplibre": "^1.0.0",
"vue": "latest",
`

**Comment by Gugustinette** [comment]
Hi,
Please provide a reproduction, with [StackBlitz](https://stackblitz.com) for example.

**Comment by CodeXiD** [comment]
Hi, @Gugustinette , sure, I created a sandbox.

https://stackblitz.com/edit/nuxt-maplibre-error-reproduction?file=app.vue

It's important to note that I was able to get the correct nuxt 3 build on `stackblitz`, when I tried to create a new nuxt 3 project on `codesandbox` - everything worked.

I just created a new nuxt project today, so maybe this only applies to the newest build

I created the project in the following way: `npx nuxi@latest init <project-name>`

**Comment by CodeXiD** [comment]
Thanks for the info and good luck

**Comment by Gugustinette** [comment]
I'll keep the issue open until this gets fixed in Nuxt and update it when needed 👍

**Comment by Gugustinette** [comment]
Fixed with Nuxt Maplibre [v1.0.1](https://github.com/Gugustinette/nuxt-maplibre/releases/tag/1.0.1)

**Comment by marr** [comment]
I believe this is still an issue. I created a new nuxt project and added the nuxt-maplibre module using the cli: `pnpx nuxi@latest module add nuxt-maplibre`. I created a client component and tried rendering it on the page. There is nothing rendered, and a console error shows:

```
Uncaught SyntaxError: The requested module '/_nuxt/node_modules/.pnpm/maplibre-gl@4.7.1/node_modules/maplibre-gl/dist/maplibre-gl.js?v=f4de1131' does not provide an export named 'LngLat' (at vue-maplibre-gl.es.js?v=f4de1131:10:10)
```

You can see the barebonese reproduction here https://github.com/marr/nuxt-maplibre

**Comment by Ayax0** [comment]
I had the same problem when using Nuxt Layers. The module was registered in my Geo Layer, but then I had the same error message in my App Layer. As a temporary fix, I added the nuxt-maplibre package as dev-dependency in my app layer. However, I hope that there will be a better solution at some point.

**Comment by Dominic-Marcelino** [comment]
Also running into this problem:

```
 node_modules/maplibre-gl/dist/maplibre-gl.js?v=a5233d6e' does not provide an export named 'LngLat'
```

When using the vue plugin directly, this can be solved by forcing an optimisation through vite:
```ts
# nuxt.config.ts
vite: {
    optimizeDeps: {
      include: [
          "maplibre-gl",
      ],
    },
  },
```

Assume something like this should work for the module too

**Comment by gabrielstuff** [comment]
With `Nuxt 3.16.2` and using the `optimizeDeps` did not help. I've got my `MglMap` wrap into a `ClientOnly` but as soon as I try to import useMap, it throw:

```
 ERROR  The requested module 'maplibre-gl' does not provide an export named 'LngLat'

    at node_modules/@indoorequal/vue-maplibre-gl/lib/lib/map.lib.ts:13:undefined:undefined:undefined)
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:181:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:264:5)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:552:26)
    at async ViteNodeRunner.interopedImport (node_modules/vite-node/dist/client.mjs:365:26)
    at async ViteNodeRunner.directRequest (node_modules/vite-node/dist/client.mjs:235:20)
    at async ViteNodeRunner.cachedRequest (node_modules/vite-node/dist/client.mjs:168:11)
    at async ViteNodeRunner.dependencyRequest (node_modules/vite-node/dist/client.mjs:216:10)
    at async modules/pages/kitchen-sink/typesense-map.vue:6:31)
    at async ViteNodeRunner.runModule (node_modules/vite-node/dist/client.mjs:342:3)
    at async ViteNodeRunner.directRequest (node_modules/vite-node/dist/client.mjs:321:3)
```

**Comment by w3cj** [comment]
I fixed this by adding the optimizeDeps option as mentioned above, but also installed `maplibre-gl` directly in my app. `nuxt-maplibre` has it as a sub dependency but vite couldn't find it.

**Comment by gabrielstuff** [comment]
@w3cj could you share your version of `Nuxt` ? 
just tried to `npm i maplibre-gl` added : 

```
vite: {
    optimizeDeps: {
      include: ['typesense-instantsearch-adapter', 'maplibre-gl'],
    },
  },
```

**Comment by gabrielstuff** [comment]
Ok, added in `nuxt.config.ts` :


```
routeRules: {
    '/my-maplibre-demo-page': {
      ssr: false,
    },
  },
```

It works fine. Just wondering why this is mandatory. We could mock the export to avoid having `ssr: false`.

**Comment by marr** [comment]
I am still experiencing this issue. Has anyone figured out what is going on? I have a fork of the nuxt-maplibre module here:
https://github.com/marr/nuxt-maplibre and I can build and run the playground just fine locally. However, when I try to use the module in an external app, the LatLng export issue occurs. Is there something wrong with the way that maplibre bundles its types, or maybe the way that the indoorequal/vue-maplibre-gl package is built?

**Comment by AlansCodeLog** [comment]
The transpile solution was working fine for me until I moved everything into a layer, then it all broke again. I tried optimized deps, etc. I use pnpm and I think this might be related to https://github.com/vitejs/vite/issues/16293 which I've been having several issues with (highlight.js also has this issue). When i hoisted the maplibregl dep, everything was fine again.
